title: The work in front of me
description: Aide memoire for what I've done in work.
url: "https://work.dfbr.co.uk"
baseurl: ""
lang: en-US

markdown: kramdown
permalink: /:categories/:title/

theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  notes:
    output: true
    permalink: /notes/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: notes
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
